"""Typed contracts for synthetic, human-decided loan precedents."""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator, model_validator

from fundermatch.clients.findociq_contract import SourceCitation


class DecisionOutcome(StrEnum):
    APPROVED = "approved"
    REJECTED = "rejected"
    APPROVED_WITH_CONDITIONS = "approved_with_conditions"


class PrecedentStatus(StrEnum):
    ACTIVE = "active"
    REVOKED = "revoked"
    SUPERSEDED = "superseded"


class FinancialProfile(BaseModel):
    """Normalized borrower facts used to construct the profile vector."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    annual_revenue_crore: Decimal = Field(gt=0)
    requested_amount_crore: Decimal = Field(gt=0)
    ebitda_margin_pct: Decimal = Field(ge=-100, le=100)
    pat_crore: Decimal = Decimal("0")
    dscr: Decimal = Field(gt=0)
    debt_to_equity: Decimal = Field(default=Decimal("0"), ge=0)
    debt_to_ebitda: Decimal = Field(ge=0)
    collateral_cover: Decimal = Field(ge=0)
    years_operating: int = Field(ge=0)
    employee_count: int = Field(gt=0)


class EvidenceMetric(BaseModel):
    """A normalized metric retaining FinDocIQ-compatible source provenance."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: Literal[
        "annual_revenue_crore",
        "ebitda_margin_pct",
        "dscr",
        "pat_crore",
        "debt_to_equity",
        "debt_to_ebitda",
        "collateral_cover",
        "years_operating",
        "employee_count",
        "borrower_name",
        "industry",
        "sub_industry",
        "region",
    ]
    value: Decimal | str
    unit: str = Field(min_length=1)
    period: str = Field(min_length=1)
    citation: SourceCitation

    @field_validator("value", mode="before")
    @classmethod
    def normalize_value(cls, value: object, info: ValidationInfo) -> Decimal | str:
        text_facts = {"borrower_name", "industry", "sub_industry", "region"}
        if info.data.get("name") in text_facts:
            text = str(value).strip()
            if not text:
                raise ValueError("text evidence cannot be empty")
            return text
        return Decimal(str(value))


class ReviewerComment(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid", str_strip_whitespace=True)

    team: Literal["finance", "operations"]
    author: str = Field(min_length=1)
    text: str = Field(min_length=1, max_length=2000)
    created_at: datetime


class DecisionOverride(BaseModel):
    """A human's explicit departure from a deterministic policy result."""

    model_config = ConfigDict(frozen=True, extra="forbid", str_strip_whitespace=True)

    criterion: str = Field(min_length=1, max_length=100)
    original_result: str = Field(min_length=1, max_length=500)
    justification: str = Field(min_length=1, max_length=1000)


class HumanDecision(BaseModel):
    """Authoritative historical decision; never generated by the AI path."""

    model_config = ConfigDict(frozen=True, extra="forbid", str_strip_whitespace=True)

    outcome: DecisionOutcome
    funder_id: str = Field(min_length=1)
    decided_by: str = Field(min_length=1)
    decided_at: datetime
    rationale: str = Field(min_length=1, max_length=2000)
    conditions: tuple[str, ...] = ()
    overrides: tuple[DecisionOverride, ...] = ()

    @model_validator(mode="after")
    def validate_conditions(self) -> HumanDecision:
        has_conditions = bool(self.conditions)
        requires_conditions = self.outcome is DecisionOutcome.APPROVED_WITH_CONDITIONS
        if has_conditions != requires_conditions:
            raise ValueError(
                "conditions must be present only for approved_with_conditions decisions"
            )
        return self


class DecidedLoanCase(BaseModel):
    """Synthetic precedent record embedded into two named Qdrant vectors."""

    model_config = ConfigDict(frozen=True, extra="forbid", str_strip_whitespace=True)

    case_id: str = Field(min_length=3, max_length=200, pattern=r"^[A-Za-z0-9][A-Za-z0-9._-]+$")
    borrower_name: str = Field(min_length=1)
    industry: str = Field(min_length=1)
    sub_industry: str = Field(default="Unclassified", min_length=1)
    region: str = Field(min_length=1)
    loan_type: str = Field(default="term_loan", pattern=r"^[a-z][a-z0-9_]{1,79}$")
    profile: FinancialProfile
    evidence: tuple[EvidenceMetric, ...] = Field(min_length=3, max_length=20)
    comments: tuple[ReviewerComment, ...] = Field(min_length=2)
    decision: HumanDecision
    lifecycle_status: PrecedentStatus = PrecedentStatus.ACTIVE
    policy_hash: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    valid_until: datetime | None = None
    supersedes_case_id: str | None = None

    @model_validator(mode="after")
    def validate_internal_consistency(self) -> DecidedLoanCase:
        metrics = {metric.name: metric.value for metric in self.evidence}
        expected = {
            "annual_revenue_crore": self.profile.annual_revenue_crore,
            "ebitda_margin_pct": self.profile.ebitda_margin_pct,
            "dscr": self.profile.dscr,
            "pat_crore": self.profile.pat_crore,
            "debt_to_equity": self.profile.debt_to_equity,
            "debt_to_ebitda": self.profile.debt_to_ebitda,
            "collateral_cover": self.profile.collateral_cover,
            "years_operating": Decimal(self.profile.years_operating),
            "employee_count": Decimal(self.profile.employee_count),
            "borrower_name": self.borrower_name,
            "industry": self.industry,
            "sub_industry": self.sub_industry,
            "region": self.region,
        }
        required = {"annual_revenue_crore", "ebitda_margin_pct", "dscr"}
        if not required <= metrics.keys() or any(
            expected[name] != value for name, value in metrics.items()
        ):
            raise ValueError("evidence metrics must exactly match normalized profile values")
        teams = {comment.team for comment in self.comments}
        if teams != {"finance", "operations"}:
            raise ValueError("each precedent requires finance and operations comments")
        if self.valid_until is not None and self.valid_until <= self.decision.decided_at:
            raise ValueError("precedent validity must extend beyond its human decision")
        return self

    def is_retrievable(self, now: datetime | None = None) -> bool:
        current = now or datetime.now(UTC)
        return self.lifecycle_status is PrecedentStatus.ACTIVE and (
            self.valid_until is None or self.valid_until > current
        )

    def profile_text(self) -> str:
        profile = self.profile
        return (
            f"Industry: {self.industry}. Sub-industry: {self.sub_industry}. "
            f"Region: {self.region}. Loan type: {self.loan_type}. "
            f"Revenue INR {profile.annual_revenue_crore} crore. "
            f"Requested amount INR {profile.requested_amount_crore} crore. "
            f"EBITDA margin {profile.ebitda_margin_pct} percent. "
            f"PAT INR {profile.pat_crore} crore. DSCR {profile.dscr}. "
            f"Debt to equity {profile.debt_to_equity}. "
            f"Debt to EBITDA {profile.debt_to_ebitda}. "
            f"Collateral cover {profile.collateral_cover}. "
            f"Operating history {profile.years_operating} years."
        )

    def comments_text(self) -> str:
        reviews = " ".join(
            f"{comment.team.title()} review: {comment.text}" for comment in self.comments
        )
        conditions = " ".join(self.decision.conditions) or "none"
        overrides = " ".join(
            f"{item.criterion}: {item.original_result}; {item.justification}"
            for item in self.decision.overrides
        ) or "none"
        return (
            f"{reviews} Human outcome: {self.decision.outcome.value}. "
            f"Human rationale: {self.decision.rationale}. "
            f"Conditions: {conditions}. Human policy overrides: {overrides}."
        )
